# Generated by Django 5.2.14 on 2026-05-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='equipment_photos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DEPARTMENT_HEAD', 'Department Head'), ('WORKER', 'Worker')], default='WORKER', max_length=20),
        ),
    ]
