# Generated by Django 5.2.12 on 2026-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_make_task_duration_nullable_and_incident_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
